#!/usr/bin/env bash
# script explainng how this script sets up nginx
# and adds a custom heade X-Served-BY

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80

# add customer header that displays which server is answering our HTTP req
x_name="server_name _;\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/server_name _;/$x_name/" /etc/nginx/sites-enabled/default
# enable changes by restarting nginx
sudo service nginx restart
