#!/usr/bin/env bash
# installing load balancer with hAproxy server

sudo apt-get -y update
sudo apt-get -y install haproxy

#match = 'frontend\n\tbind *:80\n\tdefault_backend myservers\n\n\backend myservers\n\tbalance roundrobin\n\tserver web-01 100.25.141.225\n\tserver web-02 100.25.146.253'

echo "
frontend http_front
    bind *:80
    mode http
    default_backend backend_servers


backend backend_servers
    balance roundrobin
    server 231323-web-01 100.25.141.225:80 check
    server 231323-web-02 100.25.146.253:80 check " | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

sudo service haproxy restart
