#!/usr/bin/env bash
#script to configure an Ubuntu server with requrements

cp /etc/hosts ~/hosts.newfile
echo "127.0.0.2	localhost" > ~/hosts.newfile
echo "8.8.8.8	facebook.com" >> ~/hosts.newfile
cp -f ~/hosts.newfile /etc/hosts
