#!/usr/bin/env bash
# script to generate a key pair

ssh-keygen -t rsa -b 4096 -f school -N betty -C "ericogbekene@icloud.com"


#cp ~/.ssh/id_rsa ~/school/school
#cp ~/.ssh/id_rsa.pub ~/school/school.pub
